### ISSUE TITLE
Implementation issue of "F1Function" in WCCI20-MaTMO benchmark

### ISSUE THREAD

**Issue by wushenghao8404** [intLyc/MTO-Platform#3]
In the implementation of WCCI20-MaTMO benchmark, I found that the non-linear version of F1 is
```
function F1Function = evalF1(x, f1Type)
if strcmp(f1Type, 'linear')
    A = sum(x, 2);
    F1Function = A / size(x, 2);
else
    A = sum(x.^2, 2);
    F1Function = sqrt(A);
end
end
```

which is actually the same as the **_linear_** ones with only **_one_** variable fed into evalF1 to compute f1 objective value.
The original implementation file (MMZDT.java, jMetal-version) of WCCI20 benchmark includes a non-linear transformation as

```
double F1_nonlinear(double xI[]) {
		double r = 0;

		for (int i = 0; i < xI.length; i++)
			r += (xI[i] * xI[i]);

		r = Math.sqrt(r);

		return 1 - Math.exp(-4 * r) * Math.pow(Math.sin(5 * Math.PI * r), 4);
	}
```
Given this discrepancy, maybe is there a misunderstanding or error in the non-linear transformations?

**Comment by intLyc** [comment]
Hi,

Thank you for pointing this out. I have corrected the code to ensure the proper implementation of the nonlinear version. In addition to modifying the WCCI20-MaTMO benchmark, I have also made the necessary updates to the CEC19-MaTMO and CEC21-MTMO benchmarks.

```
function F1Function = evalF1(x, f1Type)
if strcmp(f1Type, 'linear')
    A = sum(x, 2);
    F1Function = A ./ size(x, 2);
else
    A = sum(x.^2, 2);
    r = sqrt(A);
    F1Function = 1 - exp(-4 * r) .* sin(5 * pi * r).^4;
end
end
```

Fortunately, since none of the tasks in these test sets previously utilized the nonlinear version of MMZDT, the code has been functioning correctly. However, these updates will now guarantee the correctness of future extensions based on these benchmarks.

Best regards,
Yanchi
